apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: otz9aen02-python 
  janus-idp.io/tekton: otz9aen02-python
  backstage.io/kubernetes-id: otz9aen02-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: otz9aen02-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  