apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: otz9aen02-python-gitops
  description: This is GitOps manifest for otz9aen02-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: otz9aen02-python
    backstage.io/kubernetes-id: otz9aen02-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:otz9aen02-python
